### ISSUE TITLE
example return null

### ISSUE THREAD

**Issue by thib3113** [leeroybrun/node-allocine-api#5]
in your example : 
```javascript
allocine.api('movie', {code: 128188}, function(result) { console.log(result.movie.title); });
```

This return one error : 
```
e.api('movie', {code: 128188}, function(result) { console.log(result.movie.tit
                                                                    ^
TypeError: Cannot read property 'movie' of null
    at /home/thib3113/Documents/node_test/script_upload/app.js:14:76
    at IncomingMessage.<anonymous> (/home/thib3113/Documents/node_test/script_upload/node_modules/allocine-api/lib/allocine-api.js:135:25)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by leeroybrun** [comment]
Hello,

Sorry, the example of the README was not up to date...
You can find one here : https://github.com/leeroybrun/node-allocine-api/blob/master/example/movie.js

```javascript
allocine.api('movie', {code: '143067'}, function(error, result) {
	if(error) { console.log('Error : '+ error); return; }

	console.log('Success !');
	console.log(result.movie.title);
});
```

The first parameter of the callback is in fact an error object, which is null if no error happened. You can grab the result from the second parameter.

I will update the readme accordingly.
